# Generated by Django 5.0.4 on 2024-06-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedaytwogether', '0021_alter_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Members',
            field=models.IntegerField(default=0),
        ),
    ]
